### ISSUE TITLE
windows install detail

### ISSUE THREAD

**Issue by Grummfy** [jenssegers/captain#1]
hello,
Windows installation should be detailed too. Because I don't see real limitation as I know (in the way most of the time docker-compose are installed on it.

**Comment by jenssegers** [comment]
Not sure if this even works on Windows. Don't really use Windows machines 😅

**Comment by Grummfy** [comment]
mee too, but my collegues do

**Comment by jenssegers** [comment]
Travis is now building a windows executable. Looking for testers :)

**Comment by Grummfy** [comment]
will ask to my colleagues tomorrow
