### ISSUE TITLE
-d not working in latest release?

### ISSUE THREAD

**Issue by Anahkiasen** [jenssegers/captain#10]
Not sure if I'm doing something wrong but `-d` doesn't seem to work anymore for me since the latest update, could that be a possibility or was nothing related changed? :s

**Comment by jenssegers** [comment]
Indeed, looks like I broke something in the last release. Let me check.

**Comment by jenssegers** [comment]
I just pushed a new version, should be fixed in `0.3.2`!

**Comment by Anahkiasen** [comment]
Works like a charm! 👍
